version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: trio_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: trgvie
      POSTGRES_PASSWORD: trgviepass
      POSTGRES_DB: trgvie_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: trio_backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://trgvie:trgviepass@postgres:5432/trgvie_db
    ports:
      - '3001:3001'

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: trio_frontend
    depends_on:
      - backend
    ports:
      - '3000:3000'

volumes:
  pgdata:
